Задание готово
dubaua/airbnb-demo-frontend pull request #2
Opened 2017-11-11 16:24 UTC by dubaua

Переписал сетку на react-flexbox-grid.
Рефакторнул код, убрал лишние компоненты, сгруппировал что можно и вынес в общий компонент стилей, которые используются по проекту. Навел порядок в коде.
Добавил горизонтальный скролл, правда через !important, пока что, так как не разобрался, почему мое переопределение без !important не сработало.
Удивился удобности сеток, и чому я их не юзал раньше. (ну юзал, но не те).
В паре мест я залез вперед и заюзал пропы (Preview, Rating, Menu) и итерацию в компоненте, надеюсь, это не критично.

Вроде все заебись.

2017-11-11 20:28 UTC, evgenyrodionov commented
конфликты исправь

2017-11-11 20:51 UTC, dubaua commented
Исправил

2017-11-11 21:20 UTC, dubaua commented
Вот теперь исправил.

2017-11-12 10:56 UTC, imevro requested changes

2017-11-12 10:56 UTC, evgenyrodionov commented on src/Footer/index.js
> +const menu_hosting = {
camelCase

2017-11-12 10:56 UTC, evgenyrodionov commented on src/Footer/index.js
> +            <Col lg={2} lgOffset={1} md={2} mdOffset={1} xs={0}>
от меньшего к большему (xs / md / lg)
если ты снизу определил, то оно наследуется пока не переопределишь — при md={2} нет нужды ставить lg={2} или xl={2}

2017-11-12 10:56 UTC, evgenyrodionov commented on package.json
> +    "react-simple-flex-grid": "^1.1.0",
зачем

2017-11-14 16:01 UTC, imevro approved these changes

2017-11-14 16:02 UTC, merged

2017-11-14 16:02 UTC, evgenyrodionov commented
делаешь гит пулл в мастере и новый бранч от него

если уже накоммитил в другой бранч — забери через черри-пик: я мерджил через сквош (все коммиты в один засквошил), поэтому у дева и мастера разные истории